### ISSUE TITLE
[Refactor] Safe shutdown

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#395] opened 2023-07-25 02:27 UTC
## Why
In the current implementation, we use `shutdown_trigger` to send signals to the background tasks. After receiving the signal, the background task will directly `abort`. This is an unsafe implementation, because directly `abort` will stop the background task at a random `await` point, and it will directly discard all the unfinished jobs. Therefore, we need a solution to shutdown tasks safely.

## How
A feasible solution is that the stop signal is still sent to tasks as before, but after receiving the signal, task will not directly `abort`, it will actively handle its shutdown logic, complete the remaining work, and ensure that it stop running in a suitable position. after the background task stopped, the shutdown signal listener will be dropped, and the trigger of shutdown will wait until all listeners dropped. 
```rust
#[derive(Debug)]
struct Inner {
    notify: Notify,
    is_cancelled: AtomicBool,
}


#[derive(Debug)]
pub struct Trigger {
    inner: Arc<Inner>,
    rx: mpsc::Receiver<()>,
}

impl Trigger {
    pub async fn shutdown(&mut self) {
        self.inner.is_cancelled.store(true, Ordering::Relaxed);
        self.inner.notify.notify_waiters();
        _ = self.rx.recv().await;
    }
}

#[derive(Debug)]
pub struct Listener {
    inner: Arc<Inner>,
    tx: mpsc::Sender<()>,
}

impl Listener {
    pub async fn listen(&self) {
        if self.is_cancelled() {
            return;
        }
        self.inner.notify.notified().await;
    }

    pub fn is_cancelled(&self) -> bool {
        self.inner.is_cancelled.load(Ordering::Relaxed)
    }
}
```

Note: `tokio`‘s `select!` macro may have similar problems as `abort`. If a branch of `select!` is a complex `Future` with multiple `await` points, then if the current `select!` block is over caused by other branches of this `select!` block, then this complex `Future` may also stop at a random `await` point. Therefore, try not to execute complex `Future` in the `select!`, unless this `Future` allows it to stop at any `await` point.

**Comment by themanforfree** [comment] 2023-07-27 02:53
## task dependencies in `Curp`

Curp now has the following tasks:

- `gc_spec_pool` and `gc_cmd_board`: two gc tasks, we can shutdown them by `abort` safely.
- `log_persistent_task`: receive log from `log_rx` and write them to disk. it will shutdown itself when `log_tx` is dropped.
- `election_task` and `sync_follower_task`: check and send rpc requests to other nodes regularly. didn't depend on other tasks.
- `mpmc channel task` and `cmd_worker`: depend on each other by channel. as shown in the following figure.
![image](https://github.com/xline-kv/Xline/assets/56149350/0810aa2a-aa69-4c20-9b30-636b7fc3c388)
  These two parts together constitute a state machine, driven by the external `CEEvent<C>`, after receiving the shutdown signal, there will be no more `CEEvents<C>`, the state machine will continue to complete all the current job until it cannot continue, there is only one case that the state machine cannot continue to move forward, that is when the command state is `(Executed, NotSynced)`(FYI: https://github.com/xline-kv/Xline/issues/254#issuecomment-1569434108), so the `mpmc channel task` will continue run and check the current state of all commands, if the state of all remaining commands is `(Executed, NotSynced)`, then the `mpmc channel task` will shutdown itself, `cmd_worker` will also shutdown because of the channel closed.

**Comment by themanforfree** [comment] 2023-08-04 01:00
Under the premise of ensuring the normal operation of the cluster, we will only shutdown at most f nodes that the cluster can tolerate. Therefore, the closed nodes  do not need to ensure that the commands they received must be executed or after synced, and we can directly drop them without destroying the overall external guarantee of the cluster. Does this create other problems?
@rogercloud @Phoenix500526 @bsbds @iGxnon

**Comment by Phoenix500526** [comment] 2023-08-07 02:28
I haven’t identified any potential risks of doing so. But we still need to deal with the panic generated during a node crash, as mentioned in issue 370. Can you make anything of this issue? @bsbds @rogercloud @iGxnon

**Comment by Phoenix500526** [comment] 2023-08-07 05:18
This issue describes the root cause of #376, #370, and #364. And what's your concrete design?

**Comment by themanforfree** [comment] 2023-08-10 00:27
> > Under the premise of ensuring the normal operation of the cluster, we will only shut down at most f nodes that the cluster can tolerate. Therefore, the closed nodes do not need to ensure that the commands they received must be executed or after synced, and we can directly drop them without destroying the overall external guarantee of the cluster. Does this create other problems? @rogercloud @Phoenix500526 @bsbds @iGxnon
> 
> This issue describes the root cause of #376, #370, and #364. And what's your concrete design of the comment you mentioned above?

I plan to only ensure that the logs are successfully persisted in shutdown, And directly drop other content without panic

**Comment by themanforfree** [comment] 2023-08-21 02:11
# New design of shutdown

## Shutdown process
1. Client sends a shutdown request to leader.
2. The leader synchronizes shutdown logs to the cluster through the backend protocol.
3. After the shutdown log is committed, the cluster enters the shutdown state, no longer accepts external requests, Internal requests are processed normally.
4. After the cluster has finished processing the remaining requests, all nodes shutdown themselves.

## How to deal with the election during shutdown
If the cluster enters the shutdown state, all internal behavior still works correctly, include election. So we just need to wait for the election to finish before continuing with shutdown.

## Different shutdown signal
We need two different shutdown signals. one is cluster shutdown, and the other is self shutdown, cluster shutdown will wait until all commands is complete. self shutdown only needs to ensure that the log is persisted, and the other content can be discarded directly.

**Comment by Phoenix500526** [comment] 2023-08-21 06:08
How do you plan to freeze the cluster's state after the shutdown log has been committed? How should we test this functionality?

**Comment by bsbds** [comment] 2023-08-21 06:23
If a node receives a shutdown log, should it stop receiving user requests immediately or wait for the log accepted by the cluster? And please describe the recovery procedure if a shutdown log is rejected by the cluster.

**Comment by themanforfree** [comment] 2023-08-21 07:27
> How do you plan to freeze the cluster's state after the shutdown log has been committed? How should we test this functionality?

Add a check at the beginning of propose interface, if current state is shutdown, return an error directly. 
Send a lot of proposals to the cluster, than shutdown and restart the cluster, test whether the previous propose is successful

**Comment by bsbds** [comment] 2023-08-21 08:38
> > If a node receives a shutdown log, should it stop receiving user requests immediately or wait for the log to be accepted by the cluster? And please describe the recovery procedure if a shutdown log is rejected by the cluster.
> 
> It should wait for the log to be accepted by the cluster. if a shutdown log is rejected by the cluster, this log has no effect on the cluster., what needs to be restored?

That makes sense

**Comment by bsbds** [comment] 2023-08-21 08:38
LGTM

**Comment by Phoenix500526** [comment] 2023-08-21 09:42
LGTM

**Closed** 2023-09-08 01:50 UTC
