### ISSUE TITLE
[Bug]: The logging env seems to not be respected

### ISSUE THREAD

**Issue by williamdes** [xline-kv/Xline#985] opened 2024-09-08 21:22 UTC
### Description about the bug

It should understand `RUST_LOG=off` as the logging crate documents. Even `RUST_LOG=error` still outputs info and warn. 

as documented in the Docker example to run xline.

### Version

0.6.1 (Default)

### Relevant log output

```shell
2024-09-08T21:18:43.301706Z  INFO xline::utils::metrics: metrics server start on 0.0.0.0:9100
2024-09-08T21:18:43.348385Z  INFO xline::server::xline_server: name = "xline"
2024-09-08T21:18:43.348401Z  INFO xline::server::xline_server: cluster_peers = {"xline": ["127.0.0.1:2379"]}
2024-09-08T21:18:43.348636Z  INFO xline::server::xline_server: get cluster_info from local
2024-09-08T21:18:43.348711Z  INFO xline::server::xline_server: start xline server on ["http://0.0.0.0:2379"]
2024-09-08T21:18:43.348715Z  INFO xline::server::xline_server: start curp server on ["http://0.0.0.0:2380"]
2024-09-08T21:18:43.413273Z  INFO utils::task_manager: spawn CompactBg
2024-09-08T21:18:43.413301Z  INFO utils::task_manager: spawn SyncVictims
2024-09-08T21:18:43.413312Z  INFO utils::task_manager: spawn KvUpdates
2024-09-08T21:18:45.868921Z  INFO curp::server::storage::wal::storage: WAL successfully recovered
2024-09-08T21:18:45.985285Z  INFO utils::task_manager: spawn GcClientLease
2024-09-08T21:18:45.985303Z  INFO utils::task_manager: spawn Election
2024-09-08T21:18:45.985310Z  INFO utils::task_manager: spawn ConfChange
2024-09-08T21:18:45.985313Z  INFO utils::task_manager: spawn HandlePropose
2024-09-08T21:18:45.985316Z  INFO utils::task_manager: spawn AfterSync
2024-09-08T21:18:45.985378Z  WARN curp::client::stream: cannot find leader_id, refreshing state...
```

Running: `etcdctl check perf --load=xl`
It did say
```
log persistent failed: wal error, Too many open files (os error 24)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bsbds** [comment] 2024-09-11 08:36
Hi, thanks for the report! The logging issue should be fixed by https://github.com/xline-kv/Xline/pull/989.

**Comment by bsbds** [comment] 2024-09-11 08:42
> Running: `etcdctl check perf --load=xl` It did say
> 
> ```
> log persistent failed: wal error, Too many open files (os error 24)
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Please consider increasing the open files limit. I think the benchmark would open a lot of file descriptors and therefore cause the WAL writes to fail.

The panic is an intended behavior because currently we can't guarantee a write to WAL is atomic. We'll fix this in a future version.

**Closed** 2024-09-20 03:02 UTC
Labels: bug
